'use strict';

function generateEnvExample(codeRefs) {
  const lines = [
    '# Environment Variables',
    '# Generated by envguard (https://github.com/Quinnod345/envguard)',
    '#',
    `# ${codeRefs.length} variable${codeRefs.length === 1 ? '' : 's'} found in source code`,
    '',
  ];

  // Group by category (prefix before first underscore)
  const groups = new Map();
  const sorted = [...codeRefs].sort((a, b) => a.name.localeCompare(b.name));

  for (const ref of sorted) {
    const prefix = ref.name.split('_')[0] || 'OTHER';
    if (!groups.has(prefix)) groups.set(prefix, []);
    groups.get(prefix).push(ref);
  }

  for (const [prefix, refs] of groups) {
    if (groups.size > 1 && refs.length > 1) {
      lines.push(`# ${prefix}`);
    }
    for (const ref of refs) {
      lines.push(`${ref.name}=`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

module.exports = { generateEnvExample };
